html change
Pozik7/click-on-me pull request #1
Opened 2024-05-09 13:37 UTC by Pozik7

2024-05-09 15:27 UTC, VictorHaimov-HHH requested changes
Great job!!!!!

a minor fix remaining and you're good to go! 

Please include brief description & picture in the PR.

2024-05-09 15:27 UTC, VictorHaimov-HHH commented on script.js
>  var button = document.getElementById("myButton");
Avoid using `var`.
Instead use: `const `

2024-05-10 12:59 UTC, VictorHaimov-HHH commented
Nice! 
No need to show me code in description.
Also, can you align the button to be centered with the description ?

2024-05-15 17:48 UTC, Pozik7 commented
> Nice! No need to show me code in description. Also, can you align the button to be centered with the description ?

Done 
![image](https://github.com/Pozik7/click-on-me/assets/122645252/796eec16-edfd-47b4-8e40-fec923c38ac1)

2024-05-15 17:50 UTC, VicDosya approved these changes

2024-05-15 17:51 UTC, merged