random text
Pozik7/click-on-me pull request #2
Opened 2024-05-17 14:39 UTC by Pozik7

### JS
Code changed to print random text from array

![image](https://github.com/Pozik7/click-on-me/assets/122645252/0cb428b3-df54-48a8-ae0b-52f19dc12631)

2024-05-17 17:56 UTC, VicDosya requested changes
Nicely done!
Few changes remaining:
Make sure the button is ABOVE the printed text.
Also make sure only the text content of ONE div changes (not in addition). as we talked in discord.

2024-05-18 09:47 UTC, Pozik7 commented
> Nicely done! Few changes remaining: Make sure the button is ABOVE the printed text. Also make sure only the text content of ONE div changes (not in addition). as we talked in discord.

Updated please make sure this is correct.

2024-05-18 13:38 UTC, VicDosya requested changes

2024-05-18 13:38 UTC, VicDosya commented on script.js
> +  const randomIndex = Math.floor(Date.now() % messages.length);
Why `Date.now() `?
Let's go with a simple approach:
Math.floor(Math.random() * messages.length);

2024-05-18 13:45 UTC, Pozik7 commented on script.js
> +  const randomIndex = Math.floor(Date.now() % messages.length);
Done

2024-05-18 13:48 UTC, VicDosya approved these changes
Nice!

2024-05-18 13:48 UTC, merged